prow: add readme.md file for ci check
deepin-community/infra-settings pull request #160
Opened 2024-09-05 11:49 UTC by kuchune

增加prow-ci检查说明文档readme.md

2024-09-05 12:11 UTC, kuchune commented
> [!WARNING]
[Debian Check]
- 检测到敏感词lshw变动;
<details>
<summary>详情</summary>

[:confused:](https://github.com/reviews-team-test/infra-settings/raw/master/services/prow/config/jobs/images/debian-check/readme.md)


```
{
    "lshw": {
        "test.sh": [
            "echo $lshw"
        ]
    }
}
```
</details>

2024-09-05 12:14 UTC, kuchune commented
> [!WARNING]
[Debian Check]
- 检测到敏感词lshw变动;
<details>
<summary>详情</summary>

[:confused:](https://github.com/reviews-team-test/infra-settings/blob/master/services/prow/config/jobs/images/debian-check/readme.md)


```
{
    "lshw": {
        "test.sh": [
            "echo $lshw"
        ]
    }
}
```
</details>

2024-09-06 02:34 UTC, hudeng-go commented
/ok-to-test

2024-09-06 02:38 UTC, hudeng-go commented
@kuchune 评论信息里面需要带上对应检查任务的readme.

2024-09-06 02:38 UTC, hudeng-go commented
/cc @UTsweetyfish

2024-09-06 03:37 UTC, UTsweetyfish commented
## api-check/Dockerfile

三个 ADD 没有看到文件
![图片](https://github.com/user-attachments/assets/cecf4944-6ab5-46a9-9364-59ecde0ab578)

## api-check/entrypoint.sh

这个 cp 是做什么的
![图片](https://github.com/user-attachments/assets/bc3e251d-30f3-47e8-84d1-ecc942ab008b)

deepin-abigail 和 fastFilesCompare.json 不存在
![图片](https://github.com/user-attachments/assets/00527e2c-f346-4faf-b054-d33d40deda08)

## debian-check/Dockerfile

postAction.py 不存在
![图片](https://github.com/user-attachments/assets/a4c4d58a-5320-4590-ac56-f2ef71e2ea59)

## debian-check/entrypoint

1. exSuffLstForKeys unused
2. exProjectLstForEnvKeys unused
3. 为什么要做 keyJson 的检查?
4. postStep 的 assign 应该为 sysdev

## debian-check/readme.md

> 按照系统部要求,PR变更文件中不能出现"getcap,setcap,lshw,dmidecode,export,unset"的命令敏感词，如果检测匹配到对应的敏感词则显示该错误信息。

这个要求是哪里来的？

## static-check/Dockerfile

tools 目录和 postAction.py 文件不存在

![图片](https://github.com/user-attachments/assets/93af5d0c-285f-47a4-957d-9253e21ec57d)


tscancode 是什么？为什么要从 ci.uniontech.com 下载？是否可以在容器构建时编译安装？

cppcheck-2.8 版本是有限定要求吗？是否可以直接从 alpine 源安装？（apk add cppcheck）

gosec 是否可以从 alpine 源安装？（apk add）

golangci-lint 是否可以从 alpine 源安装？（apk add）

## static-check/entrypoint.sh

该检查对 C/C++ 进行了 cppcheck, tscancode，对 Go 项目进行了 Gosec 和 golangci-lint，对所有项目进行了 shellcheck

这个检查建议只在自研项目下进行，建议不对 deepin-community/* 下项目进行检查

2024-09-06 03:37 UTC, UTsweetyfish requested changes
-1, see https://github.com/deepin-community/infra-settings/pull/160#issuecomment-2333172959

2024-09-09 06:27 UTC, kuchune commented
> @kuchune 评论信息里面需要带上对应检查任务的readme.

每大的检查中包括几个子检查，我把readme的链接放在大的检查名字上了
![image](https://github.com/user-attachments/assets/f3988287-a5f1-42e1-a2dc-ec95db46c10d)

2024-09-09 06:29 UTC, kuchune commented
@UTsweetyfish 缺少的文件已经补充上传

2024-09-09 06:34 UTC, kuchune commented
> 为什么要做 keyJson 的检查?
这个属于敏感词检查，是之前gerrit中赖总这边提出的，后面增加了其他的敏感词检查，后续预计还会增加其他的敏感词检查，
参见工单：https://cooperation.uniontech.com/app/1c4062ac-cc50-4f6c-9d7d-52906b78a291/637ae9a3e01ebec272540da5/637ae9a3e01ebec272540ec1/row/071e5ab1-f0ae-44a2-9867-b501d895377b

2024-09-09 06:38 UTC, kuchune commented
> tscancode 是什么？为什么要从 ci.uniontech.com 下载？是否可以在容器构建时编译安装？

cppcheck-2.8 版本是有限定要求吗？是否可以直接从 alpine 源安装？（apk add cppcheck）

gosec 是否可以从 alpine 源安装？（apk add）

golangci-lint 是否可以从 alpine 源安装？（apk add）

@UTsweetyfish 上述工具在gerri检查中一直在使用，使用已经安装的工具，可以基本保证检查稳定运行，而不出现其他异常，后续如果验证直接安装也可以稳定运行，可以优化

2024-09-09 06:48 UTC, UTsweetyfish commented
1. deepin-abigail 没有源码
2. api-check/entrypoint.sh 里面有个 cp debian/patches 是做什么的
3. postAction.py 怎么放到 /go/ 里去了 ![图片](https://github.com/user-attachments/assets/5f63d494-c453-49d6-959c-746fa6aac58f)
4. 按照工单，dmidecode lshw 的关键字拦截是否应该是只在自研项目下进行？
5. 如果能的话 cppcheck gosec golangci-lint 还是请使用 apk add 从源进行安装
6. tscancode 为什么要从 ci.uniontech.com 下载？是否可以在容器构建时编译安装？
7. 相当多的检查在 deepin-community 下是不应被启用的，请缩减检查范围

2024-09-09 07:17 UTC, kuchune commented
> 1. deepin-abigail 没有源码
> 2. api-check/entrypoint.sh 里面有个 cp debian/patches 是做什么的
> 3. postAction.py 怎么放到 /go/ 里去了 ![图片](https://private-user-images.githubusercontent.com/124018391/365539241-5f63d494-c453-49d6-959c-746fa6aac58f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjQ5NDAsIm5iZiI6MTcyNTg2NDY0MCwicGF0aCI6Ii8xMjQwMTgzOTEvMzY1NTM5MjQxLTVmNjNkNDk0LWM0NTMtNDlkNi05NTljLTc0NmZhNmFhYzU4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNjUwNDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGQyNTA4MmZhODc4YzkwNGI3NWZmNGFmMGFlMTI0Y2M2OGIzNTJjOGI0M2Y4YTAxZWExZGRjNDg4NzFhOGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.f0yvEBYkrzz3NJraSAGEobuB4sC0lhiTIIqfYgd-gHM)
> 4. 按照工单，dmidecode lshw 的关键字拦截是否应该是只在自研项目下进行？
> 5. 如果能的话 cppcheck gosec golangci-lint 还是请使用 apk add 从源进行安装
> 6. tscancode 为什么要从 ci.uniontech.com 下载？是否可以在容器构建时编译安装？
> 7. 相当多的检查在 deepin-community 下是不应被启用的，请缩减检查范围

 1. deepin-abigail  这个工具我们这边也只拿到二进制文件，没有源码
 2.  这个是api接口检查逻辑，结合下个命令`quilt push -a`看，是应用补丁
 3.  因为使用postAction.py的运行目录是/go/latestCodeDir, entrypoint.sh里面用的也是`cp ../postAction.py .`，应该没有影响
 4. 这个我只是服从任务安排，如果只能在自研项目下进行，请联系赖总和郭斐沟通
 5. 后续验证可以的话会改进
 6. tscancode的源码中提供有二进制文件，这里只是为了在内网运行下载方便
 7. 请列出在deepin-community不应被启用的检查，我们这边需要讨论汇报给赖总决定

2024-09-09 07:27 UTC, UTsweetyfish commented
> 2. 这个是api接口检查逻辑，结合下个命令`quilt push -a`看，是应用补丁
这个最好用 `QUILT_PATCHES=debian/patches quilt --quiltrc /dev/null push -a` 来做，不需要 cp

2024-09-09 07:59 UTC, kuchune commented
> 2\. QUILT_PATCHES=debian/patches quilt --quiltrc /dev/null push -a
@UTsweetyfish 好的，我这边改一下

2024-09-12 05:21 UTC, closed without merging