feat: add deepin ci/cd cluster init settings
deepin-community/infra-settings pull request #2
Opened 2023-02-12 14:28 UTC by hudeng-go

2023-03-17 09:48 UTC, BLumia commented on README.md
> +- [deepin-virt sig（待创建）]()
这个是已创建了吧

2023-03-17 10:20 UTC, tsic404 requested changes

2023-03-17 10:20 UTC, tsic404 commented on k3s/k3s-init.sh
> +apt install -y sshpass
sudo?

2023-03-17 10:20 UTC, tsic404 commented on k3s/k3s-init.sh
> +sudo install k3sup /usr/local/bin/
install -m 755 ?

2023-03-17 10:20 UTC, tsic404 commented on k3s/k3s-init.sh
> +install k3sup /usr/local/bin/
是要整个脚本提权了？那pip3 install 的会在 `/usr/local/` 下吧

2023-03-23 07:57 UTC, hudeng-go commented on k3s/k3s-init.sh
> +install k3sup /usr/local/bin/
done.

2023-03-23 07:57 UTC, hudeng-go commented on k3s/k3s-init.sh
> +sudo install k3sup /usr/local/bin/
done.

2023-03-23 08:25 UTC, tsic404 approved these changes

2023-03-23 08:28 UTC, merged